fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: email/fosUser/resetting.html.twig
    from_email:
        address: '%env(registerEmailAdress)%'
        sender_name: '%env(registerEmailName)%'
    registration:
        confirmation:
            enabled: true
