# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        asset_adapter:
            local:
                directory: '%kernel.project_dir%/public%app.path.images%'
        intern_adapter:
            local:
                directory: '%kernel.project_dir%/data'
        policy_adapter:
            local:
                directory: '%kernel.project_dir%/data/policies'
        forms_adapter:
            local:
                directory: '%kernel.project_dir%/data/forms'
        daten_adapter:
            local:
                directory: '%kernel.project_dir%/data/daten'

    filesystems:
        asset_filesystem:
            adapter: asset_adapter
            alias: League\Flysystem\Asset
            mount: asset_filesystem
        intern_fileSystem:
            adapter: intern_adapter
            alias: League\Flysystem\Intern
            mount: intern_adapter
        policies_fileSystem:
            adapter: policy_adapter
            alias: League\Flysystem\Intern
            mount: policy_adapter
        forms_fileSystem:
            adapter: forms_adapter
            alias: League\Flysystem\Intern
            mount: forms_adapter
        daten_fileSystem:
            adapter: daten_adapter
            alias: League\Flysystem\Intern
            mount: daten_adapter