# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        asset_adapter:
            local:
              location: '%kernel.project_dir%/public%app.path.images%'
        intern_adapter:
            local:
              location: '%kernel.project_dir%/data'
        policy_adapter:
          local:
            location: '%kernel.project_dir%/data/policies'
        forms_adapter:
          local:
            location: '%kernel.project_dir%/data/forms'
        daten_adapter:
          local:
            location: '%kernel.project_dir%/data/daten'
        software_adapter:
          local:
            location: '%kernel.project_dir%/data/software'

    filesystems:
        asset:
            adapter: asset_adapter
            alias: League\Flysystem\Asset
            mount: asset
        intern:
            adapter: intern_adapter
            alias: League\Flysystem\Intern
            mount: intern
        policies:
            adapter: policy_adapter
            alias: League\Flysystem\Intern
            mount: policies
        forms:
          adapter: forms_adapter
          alias: League\Flysystem\Intern
          mount: forms
        daten:
          adapter: daten_adapter
          alias: League\Flysystem\Intern
          mount: daten
        software:
          adapter: software_adapter
          alias: League\Flysystem\Intern
          mount: software