vich_uploader:
    db_driver: orm
    storage:   flysystem
    mappings:
        profil_picture:
            uri_prefix: '%app.path.images%'
            upload_destination: intern_adapter
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
        policies:
            uri_prefix: '%app.path.images%'
            upload_destination: policy_adapter
            namer: vich_uploader.namer_uniqid
            delete_on_update: true



    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
